[package]
name = "rs-t16000m"
version = "0.1.0"
edition = "2021"
authors = ["Peter Seres"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
